-- Sales Pipelines Table
-- This is the new center of SpineDev's commercial workflow
-- A company can have multiple pipelines over time

CREATE TABLE IF NOT EXISTS sales_pipelines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    
    -- Pipeline Status
    status TEXT NOT NULL DEFAULT 'created',
    current_stage TEXT NOT NULL DEFAULT 'CREATED',
    
    -- Commercial Strategy (JSON)
    strategy JSONB,
    
    -- Stage Status Tracking
    strategy_status TEXT DEFAULT 'pending',
    messages_status TEXT DEFAULT 'pending',
    automation_status TEXT DEFAULT 'pending',
    conversation_status TEXT DEFAULT 'pending',
    
    -- Action Management
    next_action TEXT,
    next_action_date TIMESTAMPTZ,
    last_activity TIMESTAMPTZ,
    
    -- Completion
    completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sales_pipelines_company_id ON sales_pipelines(company_id);
CREATE INDEX IF NOT EXISTS idx_sales_pipelines_status ON sales_pipelines(status);
CREATE INDEX IF NOT EXISTS idx_sales_pipelines_current_stage ON sales_pipelines(current_stage);
CREATE INDEX IF NOT EXISTS idx_sales_pipelines_created_at ON sales_pipelines(created_at DESC);

-- Updated at trigger
CREATE OR REPLACE FUNCTION update_sales_pipelines_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sales_pipelines_updated_at
    BEFORE UPDATE ON sales_pipelines
    FOR EACH ROW
    EXECUTE FUNCTION update_sales_pipelines_updated_at();

-- Valid stages (can be extended later)
-- CREATED -> STRATEGY_READY -> MESSAGES_READY -> READY_TO_CONTACT -> 
-- CONTACTED -> WAITING_RESPONSE -> FOLLOW_UP -> INTERESTED -> 
-- MEETING -> CLIENT -> LOST

COMMENT ON TABLE sales_pipelines IS 'Sales Pipeline - Center of commercial workflow. Each pipeline represents a sales opportunity for a company.';
COMMENT ON COLUMN sales_pipelines.strategy IS 'Commercial strategy generated by Sales Strategy Engine (JSON)';
COMMENT ON COLUMN sales_pipelines.current_stage IS 'Current stage in the sales pipeline workflow';
COMMENT ON COLUMN sales_pipelines.next_action IS 'Next recommended action for this pipeline';
